eventhub/apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name="home"),
    path('explore/', views.explore, name="explore"),
    path('event/create/', views.create_event, name="create_event")
]

eventhub/apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('account/', views.account, name="account"),
    path('account/avatar/upload/', views.avatar_upload, name="avatar_upload"),
    path('account/avatar/delete/', views.avatar_delete, name="avatar_delete"),
    path('account/profile/', views.profile_update, name="profile_update"),
    path('account/security/', views.security_update, name="security_update"),
    path('logout/', views.logout, name="logout")
]

eventhub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('core.urls'))
]

eventhub/apps/core/models.py
from django.db import models
from django.conf import settings

class Event(models.Model):
    """
    An event created by a user.

    Attributes:
        name (str): The name of the event, required.
        date (date): The scheduled date of the event, required.
        time (time): The scheduled start time of the event, required.
        location (str): The full address or location of the event, required.
        category (str): The category of the event, required.
        description (str): A detailed description of the event (max 5000 characters), optional.
        seating_type (str): Seating type of the event (general or reserved), required.
        organizer (Profile): The user who created the event.
    """
    
    CATEGORIES = [
        ('arts', 'Arts'),
        ('business', 'Business'),
        ('family', 'Family'),
        ('food', 'Food & Drink'),
        ('music', 'Music & Concerts'),
        ('social', 'Social & Comedy'),
        ('sports', 'Sports'),
        ('tech', 'Technology'),
    ]
    
    SEATING_TYPES = [
        ('general', 'General Admission'),
        ('reserved', 'Reserved Seating'),
    ]

    name = models.CharField(max_length=50)
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=255)
    category = models.CharField(max_length=20, choices=CATEGORIES)
    description = models.TextField(blank=True)
    seating_type = models.CharField(max_length=10, choices=SEATING_TYPES)
    
    organizer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='events',
    )
    
    def __str__(self):
        return self.name


class EventImage(models.Model):
    """
    An image for event.

    Attributes:
        event (Event): The event to which this image relates.
        image_url(str): The url by which the image can be accessed.
    """
    
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='images'
    )
    image_url = models.URLField()

    def __str__(self):
        return f"Image for {self.event.name}"


class EventPriceZone(models.Model):
    """
    A price zone (range of tickets selling for the same price) for the event.
    
    Attributes:
        event (Event): The event to which this price zone relates.
        zone_name (str): The name of the price zone.
        zone_price (float): The price of the price zone in USD.
        zone_seats (int): The capacity of seats of the price zone.
    """
    
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='price_zones'
    )
    zone_name = models.CharField(max_length=50)
    zone_price = models.DecimalField(max_digits=8, decimal_places=2)
    zone_seats = models.PositiveBigIntegerField()

    def __str__(self):
        return f"Price Zone {self.zone_name} for {self.event.name} event"

eventhub/apps/core/views.py
import os
import io
import json
from dotenv import load_dotenv
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage

from .models import *
from .forms import EventInfoValidator, EventImageValidator, PriceZoneFormSet
from users.utils import cloud_upload_img

load_dotenv()

# TODO: home page for logged in user
def home(request):
    return render(request, 'core/home.html')

# TODO: dynamic event rendering + filtering
def explore(request):
    file_path = os.path.join(settings.APP_ROOT,'apps', 'core', 'data', 'dummy_data.json')
    with open(file_path, "r") as f:
        dummy_data = json.load(f)
    return render(request, 'core/explore-events.html', {'events': dummy_data, 'CDN_DOMAIN': os.getenv('CDN_DOMAIN')})


@login_required
def create_event(request):
    """
    Handle event creation.

    GET:
        - Serve create event form page.

    POST:
        Validate submitted form.
        - On errors:
            - Return create event form form with errors
        - On success:
            - Create event object (Event) with the validated provided details.
            - Create price zone objects (EventPriceZone) associated with the event.
            - Create image objects (EventImage) associated with the event.
            - Redirect to event page.
    """

    if request.method == "POST":
        user = request.user
        event_form = EventInfoValidator(request.POST)
        image_form = EventImageValidator(request.POST, request.FILES)
        price_zone_forms = PriceZoneFormSet(request.POST, prefix="zones")
        
        if ( event_form.is_valid() and image_form.is_valid() and price_zone_forms.is_valid() ):
            
            # create event object
            event = Event.objects.create(
                name=event_form.cleaned_data['name'],
                date=event_form.cleaned_data['date'],
                time=event_form.cleaned_data['time'],
                location=event_form.cleaned_data['location'],
                category=event_form.cleaned_data['category'],
                description=event_form.cleaned_data['description'],
                seating_type=event_form.cleaned_data['seating_type'],
                organizer=user
            )
            
            # create price zone object
            for zone in price_zone_forms.cleaned_data:
                if (zone):
                    EventPriceZone.objects.create(
                        event=event,
                        zone_name=zone['zone_name'],
                        zone_price=zone['zone_price'],
                        zone_seats=zone['zone_seats']
                    )
            
            # upload images and create image objects
            try:
                images = image_form.cleaned_data.get('images', [])
                fs = FileSystemStorage()
                
                for img in images:
                    file = fs.save(img.name, img)
                    file_path = fs.path(file)
                    url = cloud_upload_img(file_path)
                    fs.delete(file)
                    
                    EventImage.objects.create(
                        event=event,
                        image_url = url
                    )
            except Exception:
                event_form.add_error('images', "Something went wrong.")

            # TODO: on success redirect to event page
    else:
        event_form = EventInfoValidator()
        image_form = EventImageValidator()
        price_zone_forms = PriceZoneFormSet(prefix="zones")
    
    return render(request, 'core/create-event.html', {
            'event_form': event_form,
            'image_form': image_form,
            'price_zone_forms': price_zone_forms
        })

eventhub/apps/users/views.py
import io
from PIL import Image
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required

from .utils import *
from .forms import RegisterValidator, LoginValidator, ProfileValidator, SecurityValidator
from .models import Profile


def register(request):
    """
    Handle user registration.

    GET:
        - Serve register form page.

    POST:
        - Register user with fullname, email, password and confirm password.
        - Return register form with errors or redirect to home on success.
    """
    
    if request.method == "POST":
        form = RegisterValidator(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            avatar = ""

            # Create new user profile
            Profile.objects.create_user(
                full_name=full_name,
                email=email,
                password=password,
                avatar=avatar
            )

            # Authenticate and log in the new user
            user = authenticate(request, email=email, password=password)
            if user is not None:
                set_default_avatar(user)
                auth_login(request, user)
                return redirect('core:home')
            else:
                return redirect('users:login')
    else:
        form = RegisterValidator()
        
    return render(request, 'users/register.html', {'form': form})


def login(request):
    """
    Handle user login.

    GET:
        - Serve login form page.

    POST:
        - Authenticate user with email and password.
        - Return login form with errors or redirect to home on success.
    """
    
    if request.method == "POST":
        form = LoginValidator(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            auth_login(request, user)
            return redirect('core:home')
    else:
        form = LoginValidator()

    return render(request, 'users/login.html', {'form': form})


@login_required
def account(request):
    """
    Display the account page and handle basic profile updates.

    GET:
        - Render the account page with user information.

    Returns: Rendered account page.
    """
    return render(request, 'users/account.html')


@login_required
def avatar_upload(request):
    """Handles POST requests for avatar validation and upload."""
    
    """
    Handle avatar validation, preprocessing and upload.
    
    GET:
        - Redirects to account page (does nothing).
    
    POST:
        - Validates and processes (crops & resizes) submitted file.
        - Deletes previous avatar from cloud storage.
        - Uploads new avatar to cloud storage and stores access link in user's instance.

    Validations:
        - Must be JPG, PNG, GIF or WEBP format.
        - Must be smaller than 5MB.

    Returns: Rendered account page (with error messages if any).
    """
    
    avatar_error = None
    user = request.user
    
    if request.method == "POST":
        uploaded_file = request.FILES['imageFile']
        
        if not uploaded_file:
            avatar_error = "Error uploading the file."
        
        elif not is_valid_image_format(uploaded_file):
            avatar_error = "Unsupported image format. Please upload a JPG, PNG, GIF or WEBP file."
            
        # check file size
        elif uploaded_file.size > MAX_FILE_SIZE_MB * 1024 * 1024:
            avatar_error = "Image file is too large (max 5MB)."
            
        else:
            try:
                image = Image.open(uploaded_file)
                image_format = image.format
                
                # process new image
                image = crop_to_center(image)          # crop image 1:1 in the center
                image = image.resize(TARGET_SIZE, Image.Resampling.LANCZOS)
            
                # saves the image so it can be read or uploaded like a real file
                buffer = io.BytesIO()
                image.save(buffer, format=image_format)
                buffer.seek(0)
                
                # delete previous avatar from cloud
                cloud_delete_img(user.avatar)
            
                # set new avatar
                set_custom_avatar(user, buffer, uploaded_file.name)
                
            except Exception:
                avatar_error = "Something went wrong."

        return render(request, 'users/account.html', {'avatar_error': avatar_error})
    return redirect('users:account')


@login_required
def avatar_delete(request):
    """
    Handle deletion of the user's current avatar.
    
    GET:
        - Redirects to account page (does nothing).

    POST:
        - Deletes avatar from cloud storage.
        - Sets default avatar for the user.

    Returns: Rendered account page (with error messages if any).
    """
    
    if request.method == "POST":
        user = request.user
        avatar_error = None
                
        try:
            # delete user's avatar from could
            cloud_delete_img(user.avatar)
            
            # set default avatar
            set_default_avatar(user)
            
        except Exception:
            avatar_error = "Failed to delete an avatar."
            
        return render(request, 'users/account.html', {'avatar_error': avatar_error})
    return redirect('users:account')


@login_required
def profile_update(request):
    """Update profile information for the user (name, email, phone, location)."""
    if request.method == "POST":
        user = request.user
        form = ProfileValidator(request.POST, user=user)
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            location = form.cleaned_data['location']
            
            user.full_name = full_name
            user.email = email
            user.phone = phone
            user.location = location
            user.save()
        return render(request, 'users/account.html', {'form': form})
    return redirect('users:account')


@login_required
def security_update(request):
    """Handle user password update."""
    if request.method == "POST":
        user = request.user
        form = SecurityValidator(request.POST, user=user)
        success_password_update = None
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            success_password_update = "Your password has been updated."
        return render(request, 'users/account.html', {'form': form, 'success_password_update': success_password_update})
    return redirect('users:account')


@login_required
def logout(request):
    """Terminate current user session and redirect to the homepage."""
    auth_logout(request)
    return redirect('core:home')

eventhub/templates/users/account.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Account {% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/pages/account.css' %}" type="text/css">
{% endblock %}

{% block content %}

<section id="account" class="account-section">
    <div class="container">
        <h1>Account Settings</h1>
        <div class="account-layout">
            <aside class="account-sidebar">
                <nav class="account-nav">
                    <a href="#profile" class="account-nav-link active">
                        <i class="fas fa-user"></i> Profile Information
                    </a>
                    <a href="#security" class="account-nav-link">
                        <i class="fas fa-lock"></i> Security
                    </a>
                </nav>
            </aside>

            <div class="account-main">
                <div class="account-section-content" id="profile">
                    <div class="section-header-account">
                        <h2>Profile Information</h2>
                        <p>Manage your personal information</p>
                    </div>

                    <div class="profile-avatar-section">
                        <div class="upload-avatar-section">
                            <div class="avatar-display">
                                <img src="{{user.avatar}}" alt="User's avatar" width="120" height="120" id="avatar-img">
                            </div>

                            <div class="avatar-actions">
                                <form id="avatarUploadForm" action="{% url 'users:avatar_upload' %}" method="POST"
                                    enctype="multipart/form-data">
                                    {% csrf_token %}

                                    <input type="file" id="imageUpload" name="imageFile"
                                        accept=".jpg,.jpeg,.png,.gif,.webp" style="display: none;">
                                    <button type="button" class="btn-secondary" id="changePhotoBtn">Change
                                        Photo</button>
                                </form>

                                <form action="{% url 'users:avatar_delete' %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn-icon link-btn">Remove</button>
                                </form>
                            </div>
                        </div>

                        {% if avatar_error %}
                        <small class="form-error"> {{ avatar_error }} </small>
                        {% endif %}
                    </div>

                    <form class="account-form" action="{% url 'users:profile_update' %}" method="POST">
                        {% csrf_token %}

                        <div class="form-row">
                            <div class="form-group">
                                <label for="full_name">Full Name</label>
                                <input type="text" id="full_name" name="full_name" value="{{user.full_name}}">
                                {% if form.full_name.errors %}
                                <small class="form-error">{{ form.full_name.errors.0 }}</small>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="accountEmail">Email Address</label>
                                <input type="email" id="accountEmail" name="email" value="{{user.email}}">
                                {% if form.email.errors %}
                                <small class="form-error">{{ form.email.errors.0 }}</small>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group">
                                <label for="phoneNumber">Phone Number</label>
                                <input type="tel" id="phoneNumber" name="phone"
                                    value="{{user.phone|default_if_none:''}}">
                                {% if form.phone.errors %}
                                <small class="form-error">{{ form.phone.errors.0 }}</small>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="location">Location</label>
                                <input type="text" id="location" name="location"
                                    value="{{user.location|default_if_none:''}}">
                                {% if form.location.errors %}
                                <small class="form-error">{{ form.location.errors.0 }}</small>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn-primary">Save Changes</button>
                    </form>
                </div>

                <div class="account-section-divider"></div>

                <div class="account-section-content" id="security">
                    <div class="section-header-account">
                        <h2>Security Settings</h2>
                        <p>Manage your password and security preferences</p>
                        
                        {% if success_password_update %}
                        <small class="form-success">{{ success_password_update }}</small>
                        {% endif %}
                    </div>

                    <form class="account-form" action="{% url 'users:security_update' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="currentPassword">Current Password</label>
                            <input type="password" id="currentPassword" name="current_password" minlength="8" required>
                            {% if form.current_password.errors %}
                            <small class="form-error">{{ form.current_password.errors.0 }}</small>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="newPassword">New Password</label>
                            <input type="password" id="newPassword" name="new_password" minlength="8" required>
                            {% if form.new_password.errors %}
                            <small class="form-error">{{ form.new_password.errors.0 }}</small>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="confirmNewPassword">Confirm New Password</label>
                            <input type="password" id="confirmNewPassword" name="confirm_new_password" minlength="8"
                                required>
                            {% if form.confirm_new_password.errors %}
                            <small class="form-error">{{ form.confirm_new_password.errors.0 }}</small>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn-primary">Update Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

eventhub/templates/users/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}

<section id="login" class="auth-section">
    <div class="auth-container">
        <div class="auth-box">
            <div class="auth-header">
                <h2>Welcome Back</h2>
                <p>Log in to your Eventhub account</p>

                {% if form.non_field_errors %}
                <small class="form-error"> {{ form.non_field_errors.0 }} </small>
                {% endif %}

            </div>

            <form class="auth-form" action="{% url 'users:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="loginEmail">Email Address</label>
                    <input type="email" id="loginEmail" name="email" placeholder="your@email.com"
                        value="{{ form.email.value|default_if_none:'' }}" required>
                    {% if form.email.errors %}
                    <small class="form-error">{{ form.email.errors.0 }}</small>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="loginPassword">Password</label>
                    <input type="password" id="loginPassword" name="password" placeholder="Enter your password"
                        required>
                    {% if form.password.errors %}
                    <small class="form-error">{{ form.password.errors.0 }}</small>
                    {% endif %}
                </div>

                <div class="form-options">
                    <label class="checkbox-label">
                        <input type="checkbox" name="remember_me">
                        <span>Remember me</span>
                    </label>
                    <a href="#" class="link-text">Forgot password?</a>
                </div>

                <button type="submit" class="btn-primary btn-full">Log In</button>
            </form>

            <div class="auth-footer">
                <p>Don't have an account? <a href="{% url 'users:register' %}" class="link-text">Sign&nbsp;up</a></p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

eventhub/templates/users/register.html
{% extends 'base.html' %}

{% block title %} Registration {% endblock %}

{% block content %}

<section id="register" class="auth-section">
    <div class="auth-container">
        <div class="auth-box">
            <div class="auth-header">
                <h2>Create Your Account</h2>
                <p>Join Eventhub and start experiencing</p>
            </div>

            <form class="auth-form" action="{% url 'users:register' %}" method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <label for="registerName">Full Name</label>
                    <input type="text" id="registerName" name="full_name" placeholder="Jack Sparrow"
                        value="{{ form.full_name.value|default_if_none:'' }}" required>
                    {% if form.full_name.errors %}
                    <small class="form-error">{{ form.full_name.errors.0 }}</small>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="registerEmail">Email Address</label>
                    <input type="email" id="registerEmail" name="email" placeholder="your@email.com"
                        value="{{ form.email.value|default_if_none:'' }}" required>
                    {% if form.email.errors %}
                    <small class="form-error">{{ form.email.errors.0 }}</small>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="registerPassword">Password</label>
                    <input type="password" id="registerPassword" name="password" placeholder="At least 8 characters"
                        minlength="8" required>
                    {% if form.password.errors %}
                    <small class="form-error">{{ form.password.errors.0 }}</small>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="registerConfirmPassword">Confirm Password</label>
                    <input type="password" id="registerConfirmPassword" name="confirm_password"
                        placeholder="Re-enter your password" minlength="8" required>
                    {% if form.confirm_password.errors %}
                    <small class="form-error">{{ form.confirm_password.errors.0 }}</small>
                    {% endif %}
                </div>

                <div class="form-options">
                    <label class="checkbox-label">
                        <input type="checkbox" {% if form.terms_accepted.value %} checked {% endif %}
                            name="terms_accepted" required>
                        <span>I agree with <a href="#" class="link-text">Terms and Conditions</a></span>
                    </label>
                    {% if form.terms_accepted.errors %}
                    <small class="form-error">{{ form.terms_accepted.errors.0 }}</small>
                    {% endif %}
                </div>

                <button type="submit" class="btn-primary btn-full">Sign Up</button>
            </form>

            <div class="auth-footer">
                <p>Already have an account? <a href="{% url 'users:login' %}" class="link-text">Log&nbsp;in</a></p>
            </div>
        </div>
    </div>
</section>

{% endblock %}